{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "98049c9f_b7ddd416",
        "filename": "/COMMIT_MSG",
        "patchSetId": 8
      },
      "lineNbr": 9,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2025-07-11T13:14:53Z",
      "side": 1,
      "message": "What was the exception? And how does this fix it? We\u0027ve been restoring logs since 2017 and have never had a problem here.",
      "revId": "70a8179e4b34095d85962cd51ec5932286f896b4",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}