{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b7b08e59_e817dba2",
        "filename": "example/audit_daemon/src/audit_manager.cpp",
        "patchSetId": 5
      },
      "lineNbr": 36,
      "author": {
        "id": 1002219
      },
      "writtenOn": "2025-01-17T06:33:37Z",
      "side": 1,
      "message": "I guess this should be moved into LogEvent, because LogEvent can fail and return appropriate error.",
      "revId": "804496b8f7617680bc06cb88cb9eb16d9dbcacd5",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "228c95d9_59787f28",
        "filename": "example/audit_daemon/src/auditd.cpp",
        "patchSetId": 5
      },
      "lineNbr": 40,
      "author": {
        "id": 1002219
      },
      "writtenOn": "2025-01-17T06:33:37Z",
      "side": 1,
      "message": "This might be a nitpick, though this Init/IsIntiSuccess approach does not seems to be c++. I think if object is created there should be no other checks before using it.",
      "revId": "804496b8f7617680bc06cb88cb9eb16d9dbcacd5",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}